import {CatalogByObjectType, WorkQlChecklistInterface} from '../models';

export const mockDataWorkOrder = () => {
  const order = [
    {
      orderid: '000041178498',
      order_type: 'ZC01',
      production_start_date: '2020-02-21t00:00:00',
      production_finish_date: '2020-02-21t00:00:00',
      production_start_time: '080000',
      production_finish_time: '080000',
      actual_start_time: '000000',
      cde_code: null,
      equipment: '',
      objecttype: 'TCO',
      zzequipment: 'CDE-105741',
      eq_model: 'COOLER SRCL1000R',
      bill_no: null,
      zzcus_name: 'สำเนา',
      customer_mas: {
        orderid: '000041178498',
        customer: '0508111933',
        partn_role: '0',
        cust_name: 'ซีพี ออลล์',
        building: '31/607',
        name_co: 'ม.พฤกษา 12',
        street: 'ถนนรังสิต-นครนายก ตำบลคลองสาม',
        city1: 'ปทุมธานี',
        city2: 'อำเภอคลองหลวง',
        region: '',
        post_code: '12110',
        tel_number: '0',
        country: 'th',
        location_code: '02815',
        tradename: '6002',
        customer_class: 'B1',
        keyaccount: '0',
        longitude: 100.66451601,
        latitude: 14.02528958,
        mon_mor_from: '000000',
        mon_mor_to: '000000',
        mon_even_from: '000000',
        mon_even_to: '000000',
        tue_mor_from: '000000',
        tue_mor_to: '000000',
        tue_even_from: '000000',
        tue_even_to: '000000',
        wed_mor_from: '000000',
        wed_mor_to: '000000',
        wed_even_from: '000000',
        wed_even_to: '000000',
        thu_mor_from: '000000',
        thu_mor_to: '000000',
        thu_even_from: '000000',
        thu_even_to: '000000',
        fri_mor_from: '000000',
        fri_mor_to: '000000',
        fri_even_from: '000000',
        fri_even_to: '000000',
        sat_mor_from: '000000',
        sat_mor_to: '000000',
        sat_even_from: '000000',
        sat_even_to: '000000',
        sun_mor_from: '000000',
        sun_mor_to: '000000',
        sun_even_from: '000000',
        sun_even_to: '000000',
      },
      notification_header: {
        doc_link: null,
        orderid: '000041018513',
        notif_type: 'YR',
        notif_no: '000031018524',
        notif_date: '2020-03-13t00:00:00',
        notif_time: '131512',
        notif_incident: 'RM2002-01007',
        notif_codegroup: '',
        notif_code: 'RE01',
        notif_code_text: '',
        notif_report_by: '62001522',
        notif_longtext:
          'ประเภทเครื่อง: Cooler วันที่ทำการขอ: 16/11/2016เบอร์โทรพนักงานผู้ติดต่อลูกค้า: 0849644447 ตำาสั่งเพิ่มเติม:เอาไปตั้งสุพจน์ 5074152556',
        notif_equipment: 'W51234150901475',
        equipment_workable: null,
        zzrf_incident: '',
        zzproject: '',
        zzfirst: '',
        zzfirst_set: '',
        zzpreferdate: null,
      },
      operations: [
        {
          work_order_operation_id: 913109,
          orderid: '000041018513',
          activity: '0010',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ตรวจสอบชิ้นส่วน (เช็คอาการ)',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 30.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 10.0,
          act_start_date: '2020-03-05t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-05t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '13:00',
          work_actual_finish: '13:10',
        },
        {
          work_order_operation_id: 913110,
          orderid: '000041018513',
          activity: '0020',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ถอดชิ้นส่วนเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 30.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 10.0,
          act_start_date: '2020-03-16t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-16t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '15:50',
          work_actual_finish: '16:00',
        },
        {
          work_order_operation_id: 913111,
          orderid: '000041018513',
          activity: '0030',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ล้างอุปกรณ์และตัวเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 70.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 45.0,
          act_start_date: '2020-03-16t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-16t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '16:10',
          work_actual_finish: '16:55',
        },
        {
          work_order_operation_id: 913112,
          orderid: '000041018513',
          activity: '0040',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ทำสีตัวเครื่องและอุปกรณ์',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 150.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 18.0,
          act_start_date: '2020-03-17t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-17t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '11:10',
          work_actual_finish: '13:58',
        },
        {
          work_order_operation_id: 913113,
          orderid: '000041018513',
          activity: '0050',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ซ่อมระบบทำความเย็น',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 60.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 0.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-18t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '00:00',
          work_actual_finish: '00:00',
        },
        {
          work_order_operation_id: 913114,
          orderid: '000041018513',
          activity: '0060',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ประกอบชิ้นส่วน',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 75.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 23.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-19t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '09:30',
          work_actual_finish: '13:20',
        },
        {
          work_order_operation_id: 913115,
          orderid: '000041018513',
          activity: '0070',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ทดสอบเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 60.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 78.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-18t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '11:42',
          work_actual_finish: '13:00',
        },
        {
          work_order_operation_id: 913116,
          orderid: '000041018513',
          activity: '0080',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'qa / packing',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 40.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 4.0,
          act_start_date: '2020-03-19t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-19t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '14:30',
          work_actual_finish: '14:34',
        },
      ],
      components: [
        {
          work_order_component_id: 870412,
          orderid: '000041018513',
          reserv_no: '0',
          res_item: '0',
          movement: '',
          withdrawn: '0',
          material: '17060380',
          plant: '8017',
          stge_loc: 'T209',
          batch: 'ZNEW',
          gl_account: '',
          item_cat: '',
          item_number: '260',
          activity: '0060',
          price: 0,
          price_unit: 0,
          pur_group: '',
          matl_group: '',
          matl_desc: 'SHELF RIGHT ROD TYPE-CO-1000ECO-X',
          requirement_quantity: 10,
          requirement_quantity_unit: 'PCE',
          req_date: null,
          req_time: '',
          move_type: '261',
          commited_quan: 0,
          warranty_check: '',
          actual_quantity: 10,
          actual_quantity_unit: null,
        },
        {
          work_order_component_id: 870413,
          orderid: '000041018513',
          reserv_no: '0',
          res_item: '0',
          movement: '',
          withdrawn: '0',
          material: '17060216',
          plant: '8017',
          stge_loc: 'T209',
          batch: 'ZNEW',
          gl_account: '',
          item_cat: '',
          item_number: '250',
          activity: '0060',
          price: 0,
          price_unit: 0,
          pur_group: '',
          matl_group: '',
          matl_desc: 'ซองพลาสติก-SU-GEN',
          requirement_quantity: 1,
          requirement_quantity_unit: 'PCE',
          req_date: null,
          req_time: '',
          move_type: '261',
          commited_quan: 0,
          warranty_check: '',
          actual_quantity: 1,
          actual_quantity_unit: null,
        },
        {
          work_order_component_id: 870416,
          orderid: '000041018513',
          reserv_no: '0',
          res_item: '0',
          movement: '',
          withdrawn: '0',
          material: '17047174',
          plant: '8017',
          stge_loc: 'T209',
          batch: 'ZNEW',
          gl_account: '',
          item_cat: '',
          item_number: '200',
          activity: '0060',
          price: 0,
          price_unit: 0,
          pur_group: '',
          matl_group: '',
          matl_desc: 'PAINTED FRONT PANEL SRC1000ECO',
          requirement_quantity: 1,
          requirement_quantity_unit: 'PCE',
          req_date: null,
          req_time: '',
          move_type: '261',
          commited_quan: 0,
          warranty_check: '',
          actual_quantity: 1,
          actual_quantity_unit: null,
        },
        {
          work_order_component_id: 870418,
          orderid: '000041018513',
          reserv_no: '0',
          res_item: '0',
          movement: '',
          withdrawn: '0',
          material: '17047162',
          plant: '8017',
          stge_loc: 'T209',
          batch: 'ZNEW',
          gl_account: '',
          item_cat: '',
          item_number: '180',
          activity: '0060',
          price: 0,
          price_unit: 0,
          pur_group: '',
          matl_group: '',
          matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
          requirement_quantity: 2,
          requirement_quantity_unit: 'PCE',
          req_date: null,
          req_time: '',
          move_type: '261',
          commited_quan: 0,
          warranty_check: '',
          actual_quantity: 2,
          actual_quantity_unit: null,
        },
      ],
      historyorder_header: [
        {
          work_order_historyorder_header_id: 2233224,
          orderid: '000041450263',
          orderid_history: '000041449486',
          customer: '0501317359',
          notif_no: '000031471734',
          notif_longtext: '',
          order_type: 'ZC04',
          notif_date: '2021-06-02T00:00:00',
          notif_time: '181000',
          notif_incident: '000041449129',
          equipment: 'CDE-008581',
          notif_codegroup: 'INSTALL1',
          notif_code: 'C004',
          notif_code_text: 'ทดแทนเครื่องซ่อม',
          notif_objpart_codegroup: 'INSTALL1',
          notif_objpart_code: '',
          notif_objpart_text: '',
          notif_problem_codegroup: 'INSTALL1',
          notif_problem_codeg: '',
          notif_problem_text: '',
          notif_cause_codegroup: 'INSTALL1',
          notif_cause_codeg: '',
          notif_cause_text: '',
          notif_act_codegroup: 'INSTALL1',
          notif_act_codeg: '',
          notif_act_text: '',
          history_sparepart: [
            {
              material: '15000361',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000362',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000363',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
          ],
        },
        {
          work_order_historyorder_header_id: 2233223,
          orderid: '000041450263',
          orderid_history: '000041449129',
          customer: '0501317359',
          notif_no: '000031471392',
          notif_longtext: '',
          order_type: 'ZC03',
          notif_date: '2021-06-02T00:00:00',
          notif_time: '105000',
          notif_incident: '21060201853',
          equipment: 'TNTC-51330232',
          notif_codegroup: 'TFCB',
          notif_code: 'F026',
          notif_code_text: 'น้ำหวานรั่ว-TFCB-F026',
          notif_objpart_codegroup: 'TFCB',
          notif_objpart_code: 'C901',
          notif_objpart_text: 'เสียจากอุปกรณ์ภายในเครื่อง',
          notif_problem_codegroup: 'TFCB',
          notif_problem_codeg: 'D241',
          notif_problem_text: 'Syrup รั่ว',
          notif_cause_codegroup: 'TFCB',
          notif_cause_codeg: 'C396',
          notif_cause_text: 'Foam Pack รั่ว',
          notif_act_codegroup: 'TFCB',
          notif_act_codeg: 'A217',
          notif_act_text: 'เปลี่ยนเครื่องFOAMPACKรั่ว',
          history_sparepart: [
            {
              material: '15000361',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000362',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000363',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
          ],
        },
        {
          work_order_historyorder_header_id: 2233225,
          orderid: '000041450263',
          orderid_history: '000041449487',
          customer: '0501317359',
          notif_no: '000031471735',
          notif_longtext: '',
          order_type: 'ZC09',
          notif_date: '2021-06-02T00:00:00',
          notif_time: '171000',
          notif_incident: '000041449129',
          equipment: 'TNTC-51330232',
          notif_codegroup: 'REMOVE1',
          notif_code: 'C004',
          notif_code_text: 'ทดแทนเครื่องซ่อม',
          notif_objpart_codegroup: 'REMOVE1',
          notif_objpart_code: '',
          notif_objpart_text: '',
          notif_problem_codegroup: 'REMOVE1',
          notif_problem_codeg: '',
          notif_problem_text: '',
          notif_cause_codegroup: 'REMOVE1',
          notif_cause_codeg: '',
          notif_cause_text: '',
          notif_act_codegroup: 'REMOVE1',
          notif_act_codeg: '',
          notif_act_text: '',
          history_sparepart: [
            {
              material: '15000361',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000362',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
            {
              material: '15000363',
              matl_desc: 'DOOR GASKET BB 1386X505.5 SRC1000 200957',
              quantity: 10.0,
              unit: 0.0,
            },
          ],
        },
      ],
    },
    {
      orderid: '000040340899',
      order_type: 'ZC01',
      production_start_date: '2020-02-21t00:00:00',
      production_finish_date: '2020-02-21t00:00:00',
      production_start_time: '080000',
      production_finish_time: '080000',
      actual_start_time: '000000',
      cde_code: null,
      equipment: '',
      objecttype: 'TCO',
      zzequipment: 'CDE-105741',
      eq_model: 'COOLER SRCL1000R',
      bill_no: null,
      zzcus_name: 'สำเนา',
      customer_mas: {
        orderid: '000040340899',
        customer: '0501353484',
        partn_role: '0',
        cust_name: 'จำรัส ดีมีชาติ',
        building: '230',
        name_co: 'ข้างอู่อารี',
        street: 'ถนนพระราม4 แขวงคลองเตย',
        city1: 'กรุงเทพมหานคร',
        city2: 'เขตคลองเตย',
        region: '',
        post_code: '10110',
        tel_number: '0',
        country: 'thx',
        location_code: '',
        tradename: '6999',
        customer_class: 'D1',
        keyaccount: '0',
        longitude: 100.5674,
        latitude: 13.7209,
        mon_mor_from: '000000',
        mon_mor_to: '000000',
        mon_even_from: '000000',
        mon_even_to: '000000',
        tue_mor_from: '000000',
        tue_mor_to: '000000',
        tue_even_from: '000000',
        tue_even_to: '000000',
        wed_mor_from: '000000',
        wed_mor_to: '000000',
        wed_even_from: '000000',
        wed_even_to: '000000',
        thu_mor_from: '000000',
        thu_mor_to: '000000',
        thu_even_from: '000000',
        thu_even_to: '000000',
        fri_mor_from: '000000',
        fri_mor_to: '000000',
        fri_even_from: '000000',
        fri_even_to: '000000',
        sat_mor_from: '000000',
        sat_mor_to: '000000',
        sat_even_from: '000000',
        sat_even_to: '000000',
        sun_mor_from: '000000',
        sun_mor_to: '000000',
        sun_even_from: '000000',
        sun_even_to: '000000',
      },
      notification_header: {
        doc_link: null,
        orderid: '000041018513',
        notif_type: 'YR',
        notif_no: '000031018524',
        notif_date: '2020-03-13t00:00:00',
        notif_time: '131512',
        notif_incident: 'RM2002-01007',
        notif_codegroup: '',
        notif_code: 'RE01',
        notif_code_text:
          'ประเภทเครื่อง: Cooler วันที่ทำการขอ: 16/11/2016เบอร์โทรพนักงานผู้ติดต่อลูกค้า: 0849644447 ตำาสั่งเพิ่มเติม:เอาไปตั้งสุพจน์ 5074152556',
        notif_report_by: '62001522',
        notif_longtext: '',
        notif_equipment: 'W51234150901475',
        equipment_workable: null,
        zzrf_incident: '',
        zzproject: '',
        zzfirst: '',
        zzfirst_set: '',
        zzpreferdate: null,
      },
      operations: [
        {
          work_order_operation_id: 913109,
          orderid: '000041018513',
          activity: '0010',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ตรวจสอบชิ้นส่วน (เช็คอาการ)',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 30.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 10.0,
          act_start_date: '2020-03-05t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-05t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '13:00',
          work_actual_finish: '13:10',
        },
        {
          work_order_operation_id: 913110,
          orderid: '000041018513',
          activity: '0020',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ถอดชิ้นส่วนเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 30.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 10.0,
          act_start_date: '2020-03-16t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-16t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '15:50',
          work_actual_finish: '16:00',
        },
        {
          work_order_operation_id: 913111,
          orderid: '000041018513',
          activity: '0030',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ล้างอุปกรณ์และตัวเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 70.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 45.0,
          act_start_date: '2020-03-16t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-16t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '16:10',
          work_actual_finish: '16:55',
        },
        {
          work_order_operation_id: 913112,
          orderid: '000041018513',
          activity: '0040',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ทำสีตัวเครื่องและอุปกรณ์',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 150.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 18.0,
          act_start_date: '2020-03-17t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-17t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '11:10',
          work_actual_finish: '13:58',
        },
        {
          work_order_operation_id: 913113,
          orderid: '000041018513',
          activity: '0050',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ซ่อมระบบทำความเย็น',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 60.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 0.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-18t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '00:00',
          work_actual_finish: '00:00',
        },
        {
          work_order_operation_id: 913114,
          orderid: '000041018513',
          activity: '0060',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ประกอบชิ้นส่วน',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 75.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 23.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-19t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '09:30',
          work_actual_finish: '13:20',
        },
        {
          work_order_operation_id: 913115,
          orderid: '000041018513',
          activity: '0070',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'ทดสอบเครื่อง',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 60.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 78.0,
          act_start_date: '2020-03-18t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-18t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '11:42',
          work_actual_finish: '13:00',
        },
        {
          work_order_operation_id: 913116,
          orderid: '000041018513',
          activity: '0080',
          control_key: '',
          work_cntr: 'brtt209',
          work_center: null,
          plant: '8017',
          description: 'qa / packing',
          number_of_capacities: 0,
          acttype: 'y20001',
          duration_normal: 40.0,
          duration_normal_unit: 'min',
          work_activity: 0.0,
          un_work: '',
          conf_no: '0',
          work_actual: 4.0,
          act_start_date: '2020-03-19t00:00:00',
          act_start_time: '000000',
          act_end_date: '2020-03-19t00:00:00',
          act_end_time: '000000',
          system_status_text: null,
          work_actual_start: '14:30',
          work_actual_finish: '14:34',
        },
      ],
    },
  ];

  return order;
};

export const useFetchWorkOrder = () => {
  const order = [
    {
      orderid: '000041178498',
      order_type: 'ZC01',
      production_start_date: '2020-02-21t00:00:00',
      production_finish_date: '2020-02-21t00:00:00',
      production_start_time: '080000',
      production_finish_time: '080000',
      customer_mas: {
        orderid: '000041178498',
        customer: '0508111933',
        partn_role: '0',
        cust_name: 'ซีพี ออลล์',
        building: '31/607',
        name_co: 'ม.พฤกษา 12',
        street: 'ถนนรังสิต-นครนายก ตำบลคลองสาม',
        city1: 'ปทุมธานี',
        city2: 'อำเภอคลองหลวง',
        region: '',
        post_code: '12110',
        tel_number: '0',
        country: 'th',
        location_code: '02815',
        tradename: '6002',
        customer_class: 'B1',
        keyaccount: '0',
        longitude: 100.66451601,
        latitude: 14.02528958,
        mon_mor_from: '000000',
        mon_mor_to: '000000',
        mon_even_from: '000000',
        mon_even_to: '000000',
        tue_mor_from: '000000',
        tue_mor_to: '000000',
        tue_even_from: '000000',
        tue_even_to: '000000',
        wed_mor_from: '000000',
        wed_mor_to: '000000',
        wed_even_from: '000000',
        wed_even_to: '000000',
        thu_mor_from: '000000',
        thu_mor_to: '000000',
        thu_even_from: '000000',
        thu_even_to: '000000',
        fri_mor_from: '000000',
        fri_mor_to: '000000',
        fri_even_from: '000000',
        fri_even_to: '000000',
        sat_mor_from: '000000',
        sat_mor_to: '000000',
        sat_even_from: '000000',
        sat_even_to: '000000',
        sun_mor_from: '000000',
        sun_mor_to: '000000',
        sun_even_from: '000000',
        sun_even_to: '000000',
      },
      notification_header: {
        doc_link: null,
        orderid: '000041018513',
        notif_type: 'YR',
        notif_no: '000031018524',
        notif_date: '2020-03-13t00:00:00',
        notif_time: '131512',
        notif_incident: '',
        notif_codegroup: '',
        notif_code: '',
        notif_code_text: '',
        notif_report_by: '62001522',
        notif_longtext: '',
        notif_equipment: 'W51234150901475',
        equipment_workable: null,
        zzrf_incident: '',
        zzproject: '',
        zzfirst: '',
        zzfirst_set: '',
        zzpreferdate: null,
      },
    },
    {
      orderid: '000040340899',
      order_type: 'ZC01',
      production_start_date: '2020-02-21t00:00:00',
      production_finish_date: '2020-02-21t00:00:00',
      production_start_time: '080000',
      production_finish_time: '080000',
      customer_mas: {
        orderid: '000040340899',
        customer: '0501353484',
        partn_role: '0',
        cust_name: 'จำรัส ดีมีชาติ',
        building: '230',
        name_co: 'ข้างอู่อารี',
        street: 'ถนนพระราม4 แขวงคลองเตย',
        city1: 'กรุงเทพมหานคร',
        city2: 'เขตคลองเตย',
        region: '',
        post_code: '10110',
        tel_number: '0',
        country: 'thx',
        location_code: '',
        tradename: '6999',
        customer_class: 'D1',
        keyaccount: '0',
        longitude: 100.5674,
        latitude: 13.7209,
        mon_mor_from: '000000',
        mon_mor_to: '000000',
        mon_even_from: '000000',
        mon_even_to: '000000',
        tue_mor_from: '000000',
        tue_mor_to: '000000',
        tue_even_from: '000000',
        tue_even_to: '000000',
        wed_mor_from: '000000',
        wed_mor_to: '000000',
        wed_even_from: '000000',
        wed_even_to: '000000',
        thu_mor_from: '000000',
        thu_mor_to: '000000',
        thu_even_from: '000000',
        thu_even_to: '000000',
        fri_mor_from: '000000',
        fri_mor_to: '000000',
        fri_even_from: '000000',
        fri_even_to: '000000',
        sat_mor_from: '000000',
        sat_mor_to: '000000',
        sat_even_from: '000000',
        sat_even_to: '000000',
        sun_mor_from: '000000',
        sun_mor_to: '000000',
        sun_even_from: '000000',
        sun_even_to: '000000',
      },
    },
  ];
  const orderData = [
    {
      days: '21 ก.พ ศุกร์',
      order: [
        {
          orderCode: '4232452424',
          type: 'ZC01',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#2a60bb',
          roleType: 'visit'
        },
        {
          orderCode: '4232452424',
          type: 'ZC02',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#2a60bb',
          roleType: 'inspector'
        },
      ],
    },
    {
      days: '22 ก.พ เสาร์',
      order: [
        {
          orderCode: '4232452424',
          type: 'ZC03',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#7e2199',
          roleType: 'inspector'
        },
        {
          orderCode: '4232452424',
          type: 'ZC04',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#7e2199',
          roleType: 'visit'
        },
      ],
    },
    {
      days: '22 ก.พ อาทิตย์',
      order: [
        {
          orderCode: '4232452424',
          type: 'ZC03',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#e61711',
          roleType: 'inspector'
        },
        {
          orderCode: '4232452424',
          type: 'ZC04',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#e61711',
          roleType: 'inspector'
        },
      ],
    },
    {
      days: '23 ก.พ จันทร์',
      order: [
        {
          orderCode: '4232452424',
          type: 'ZC03',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#f8a834',
          roleType: 'visit'
        },
        {
          orderCode: '4232452424',
          type: 'ZC04',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#f8a834',
          roleType: 'visit'
        },
      ],
    },
    {
      days: '24 ก.พ อังคาร',
      order: [
        {
          orderCode: '4232452424',
          type: 'ZC03',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#FF1493',
          roleType: 'visit'
        },
        {
          orderCode: '4232452424',
          type: 'ZC04',
          description: 'แจ้งให้ตรวจเช็ต/PMเครื่อง-TPX-A035',
          date: ' 22/02/2020',
          time: '16:00 น.',
          account:
            'ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)ซีพี ออลล์ ปดท.เชียงรากน้อย(ขาอ (Key Account)(อำเภอสามโดก ปทุมธานี)',
          colorStatus: '#FF1493',
          roleType: 'visit'
        },
      ],
    },
  ];
  return orderData;
};

export const workQlChecklist = (type: string) => {
  const qlChecklistData: WorkQlChecklistInterface[] = [
    {
      type: 'TFCB',
      checkList: [
        {
          title: 'สถานที่ติดตั้งเครื่อง(Location)',
          type: 'L1',
          item: [
            {
              title: 'ความสะอาดรอบๆ บริเวณที่ตั้ง  ปราศจากสัตว์ภาหนะ',
              type: 'radio',
              field_name: 'cleanliness',
              code: '',
            },
            {
              title: 'การระบายอากาศรอบตัวเครื่อง',
              type: 'radio',
              field_name: 'ventilation',
              code: '',
            },
            {
              title: 'พื้นที่ติดตั้งระยะห่างจากผนัง',
              type: 'radio',
              field_name: 'distance',
              code: '',
            },
            {
              title: 'พื้นที่ติดตั้ง(ไม่ลาดเอียง)',
              type: 'radio',
              field_name: 'space',
              code: '',
            },
            {
              title: 'เต้ารับไฟฟ้าๅๅๅๅๅๅๅๅ',
              type: 'radio',
              field_name: 'electrical_socket',
              code: '',
            },
            {
              title: 'ตรวจสอบระบบไฟฟ้า ( Volt)',
              type: 'input',
              field_name: 'power_system',
              code: '',
            },
          ],
        },
        {
          title: 'ระบบน้ำ/แหล่งจ่ายน้ำ(Water System)',
          type: 'W3',
          item: [
            {
              title: 'น้ำประปา',
              type: 'radio',
              field_name: 'tap_water',
              code: '',
            },
            {
              title: 'น้ำบาดาล',
              type: 'radio',
              field_name: 'underground_water',
              code: '',
            },
            {
              title: 'แรงดันน้ำก่อนเข้าชุดกรอง (Psi.)',
              type: 'input',
              field_name: 'water_pressure_in',
              code: '',
            },
            {
              title: 'แรงดันน้ำออกจากชุดกรอง (Psi.)',
              type: 'input',
              field_name: 'water_pressure_out',
              code: '',
            },
            {
              title: 'ไส้กรองตะกอน(EC)หมดอายุวันที่',
              type: 'input',
              field_name: 'filter_expiration_ec',
              code: '',
            },
            {
              title: 'ไส้กรองกลิ่น(MC)หมดอายุวันที่',
              type: 'input',
              field_name: 'filter_expiration_mc',
              code: '',
            },
            {
              title: 'ไส้กรองIMFหมดอายุวันที่',
              type: 'input',
              field_name: 'filter_expiration_imf',
              code: '',
            },
            {
              title: 'ตรวจเช็คการรั่วซึมของระบบน้ำ',
              type: 'radio',
              field_name: 'check_water_system_leaks',
              code: '',
            },
          ],
        },
        {
          title: 'ระบบน้ำหวาน(Syrup System)',
          type: 'S4',
          item: [
            {
              title: 'ตรวจสอบสภาพกล่องน้ำหวาน ไม่แตก,ไม่มีน้ำหวานรั่วไหล',
              type: 'radio',
              field_name: 'check_nectar_box',
              code: '',
            },
            {
              title: 'ตรวจสอบ Connector BIB',
              type: 'radio',
              field_name: 'check_connector_bib',
              code: '',
            },
            {
              title:
                'ตรวจสอบสาย Syrup มีป้าย ชี้บ่งผลิตภัณฑ์ชัดเจน  (Line marker)',
              type: 'radio',
              field_name: 'check_syrup',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของปั้มSyrup',
              type: 'radio',
              field_name: 'check_pump_syrup',
              code: '',
            },
            {
              title: 'ระยะสายน้ำหวานจากจุดติดตั้ง BIB ไปหาเครื่อง(เมตร)',
              type: 'input',
              field_name: 'system_bib',
              code: '',
            },
            {
              title: 'ตรวจเช็คการรั่วซึมของระบบน้ำหวาน',
              type: 'radio',
              field_name: 'check_water_nectar_system_leaks',
              code: '',
            },
          ],
        },
        {
          title: 'ระบบแรงดัน(Co2 System)',
          type: 'S5',
          item: [
            {
              title: 'ตรวจเช็คความเหมาะสมของพื้นที่ติดตั้งถังCO2',
              type: 'radio',
              field_name: 'check_installation_area',
              code: '',
            },
            {
              title: 'ตรวจเช็คสภาพของ Pressure gauges ',
              type: 'radio',
              field_name: 'check_pressure_gauges',
              code: '',
            },
            {
              title: 'ตรวจเช็คปริมาณ CO2 ในถัง (Psi.)',
              type: 'input',
              field_name: 'check_quantity',
              code: '',
            },
            {
              title: 'ตรวจเช็ค High Pressure / Center Gauge (Psi.)',
              type: 'input',
              field_name: 'check_high_pressure',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Low Pressure guage BIB(Psi.)',
              type: 'input',
              field_name: 'check_low_pressure',
              code: '',
            },
            {
              title: 'ระยะสายCo2จากจุดติดตั้งถัง Co2 ไปหาเครื่อง(เมตร)',
              type: 'input',
              field_name: 'cable_distance_co2',
              code: '',
            },
            {
              title: 'ตรวจเช็คการรั่วซึมของระบบCo2',
              type: 'radio',
              field_name: 'system_leaks_co2',
              code: '',
            },
          ],
        },
        {
          title: 'รายการตรวจเช็คเครื่อง(Machine)',
          type: 'C6',
          item: [
            {
              title: 'ตรวจเช็คปลั๊กไฟ',
              type: 'radio',
              field_name: 'check_power_plug',
              code: '',
            },
            {
              title: 'ตรวจเช็คLow Regulator ในเครื่อง (Psi.)',
              type: 'radio',
              field_name: 'check_low_regulator',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของ Carbonator Pump',
              type: 'input',
              field_name: 'check_carbonator_pump',
              code: '',
            },
            {
              title: 'ตรวจเช็ค   Viscosity 1',
              type: 'input',
              field_name: 'check_viscosity_1',
              code: '',
            },
            {
              title: 'ตรวจเช็ค   Viscosity 2',
              type: 'input',
              field_name: 'check_viscosity_2',
              code: '',
            },
            {
              title: 'ตรวจเช็ค   Defrost time',
              type: 'input',
              field_name: 'check_defrost_time',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของมอเตอร์ระบายความร้อน',
              type: 'radio',
              field_name: 'check_cooling_motor',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของมอเตอร์เกียร์',
              type: 'radio',
              field_name: 'check_gear_motor.',
              code: '',
            },
            {
              title: 'ตรวจเช็คการรั่วซึมเช็ควาล์วหน้า Door Freeze',
              type: 'radio',
              field_name: 'check_door_freeze',
              code: '',
            },
            {
              title: 'ตรวจเช็ดการทำงานของ Agitator Motor',
              type: 'radio',
              field_name: 'check_agitator_motor',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Ice Bin พร้อมใช้หรือไม่ ( Condent รอบเครื่อง)',
              type: 'radio',
              field_name: 'check_ice_bin',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Water Curtain',
              type: 'radio',
              field_name: 'check_water_curtain',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Bin Switch',
              type: 'radio',
              field_name: 'check_bin_switch',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Water Level Probe',
              type: 'radio',
              field_name: 'check_water_level_probe',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Ice Thickness Sensor',
              type: 'radio',
              field_name: 'check_ice_thickness_sensor',
              code: '',
            },
            {
              title:
                'ตรวจเช็คการทำงานของ Evap (ลักษณะของก้อนน้ำแข็งเต็มก้อนหรือไม่)',
              type: 'radio',
              field_name: 'check_evap',
              code: '',
            },
            {
              title: 'ตรวจเช็คถาดรองน้ำและท่อจ่ายน้ำทิ้ง',
              type: 'radio',
              field_name: 'check_water_tray ',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Filling Solenoid Valve, Dump Valve',
              type: 'radio',
              field_name: 'check_filling_solenoid',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Compressor และวัดกระแส (Amp.)',
              type: 'radio',
              field_name: 'check_compressor',
              code: '',
            },
            {
              title: 'ตรวจเช็คจุดต่อสายไฟฟ้าเข้าเครื่อง',
              type: 'radio',
              field_name: 'check_connect_point_cable',
              code: '',
            },
            {
              title: 'ตรวจเช็คระยะเวลาช่วง Freeze Cycle (นาที)',
              type: 'radio',
              field_name: 'check_freeze_cycle',
              code: '',
            },
            {
              title: 'ตรวจเช็คระยะเวลาช่วง Harvest Cycle (นาที)',
              type: 'radio',
              field_name: 'check_harvest_cycle',
              code: '',
            },
            {
              title: 'ตรวจเช็คจำนวนน็อตทั้งหมดของเครื่องมี (ตัว)',
              type: 'radio',
              field_name: 'check_nut_total',
              code: '',
            },
            {
              title: 'ตรวจเช็คน๊อตอยู่ในสภาพแน่น จำนวน (ตัว)',
              type: 'radio',
              field_name: 'check_tight_condition',
              code: '',
            },
            {
              title: 'ตรวจเช็คความสะอาดภายในถังเก็บน้ำแข็ง',
              type: 'radio',
              field_name: 'check_clean_in_ice_bucket',
              code: '',
            },
            {
              title: 'ตรวจเช็คความสะอาดภายนอกถังเก็บน้ำแข็ง',
              type: 'radio',
              field_name: 'check_clean_out_ice_bucket',
              code: '',
            },
            {
              title: 'ตรวจเช็คสภาพใบกวาดน้ำแข็ง',
              type: 'radio',
              field_name: 'check_sweeping_ice',
              code: '',
            },
            {
              title: 'ตรวจเช็คไมโครสวิตซ์ เปิด-ปิด น้ำแข็ง',
              type: 'radio',
              field_name: 'check_micro_switch',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของโซลินอยล์',
              type: 'radio',
              field_name: 'check_solenoid',
              code: '',
            },
            {
              title: 'ตรวจเช็คสปริงหัวจ่ายน้ำแข็งในเครื่องจ่าย',
              type: 'radio',
              field_name: 'check_nozzle_spring',
              code: '',
            },
            {
              title: 'ตรวจเช็คสลักยึดแกนใบกวาดน้ำแข็ง',
              type: 'radio',
              field_name: 'check_axis_mounting_pin',
              code: '',
            },
            {
              title: 'ตรวจเช็คฝา เปิด-ปิด น้ำแข็ง',
              type: 'radio',
              field_name: 'check_lid_on_off',
              code: '',
            },
            {
              title: 'ตรวจเช็คถาดน้ำทิ้ง (ไม่รั่ว / ไม่รั่ว)',
              type: 'radio',
              field_name: 'check_drain_tray',
              code: '',
            },
            {
              title: 'ตรวจเช็คท่อน้ำทิ้ง (ไม่รั่ว / ไม่รั่ว)',
              type: 'radio',
              field_name: 'check_sewer_pipe',
              code: '',
            },
            {
              title: 'ตรวจเช็ค Condent รอบเครื่อง',
              type: 'radio',
              field_name: 'check_condent',
              code: '',
            },
            {
              title: 'ตรวจเช็คหลอดไฟ',
              type: 'radio',
              field_name: 'check_light_bulb',
              code: '',
            },
            {
              title: 'ตรวจเช็คสวิทซ์ปุ่มกดหน้าตู้',
              type: 'radio',
              field_name: 'check_switch_pushbutton',
              code: '',
            },
            {
              title: 'ตรวจเช็คโล้โก้สินค้า',
              type: 'radio',
              field_name: 'check_logo_product',
              code: '',
            },
            {
              title: 'ตรวจเช็คชุดจ่ายกระป๋อง',
              type: 'radio',
              field_name: 'check_canned',
              code: '',
            },
            {
              title: 'ตรวจเช็คกุญแจเปิด-ปิดตู้',
              type: 'radio',
              field_name: 'check_key_on_off',
              code: '',
            },
            {
              title: 'ตรวจเช็คยางขอบประตู',
              type: 'radio',
              field_name: 'check_door_seal',
              code: '',
            },
            {
              title: 'ตรวจเช็คตะแกรงฝาครอบหลังตู้',
              type: 'radio',
              field_name: 'check_grille_cover',
              code: '',
            },
            {
              title: 'ตรวจเช็คปุ่มกดคืนเหรียญ',
              type: 'radio',
              field_name: 'check_button_return_coins',
              code: '',
            },
            {
              title: 'ตรวจเช็คมอเตอร์Ven',
              type: 'radio',
              field_name: 'check_mornitor_van',
              code: '',
            },
            {
              title: 'ตรวจเช็คฝาปิดช่องจ่ายสินค้า',
              type: 'radio',
              field_name: 'check_product_compartment_cover',
              code: '',
            },
            {
              title: 'ตรวจเช็คสภาพตู้ภายนอก(มีรอย / ไม่มีรอย)',
              type: 'radio',
              field_name: 'check_in_storage_condition',
              code: '',
            },
            {
              title: 'ตรวจเช็คสภาพตู้ภายใน(มีรอย / ไม่มีรอย)',
              type: 'radio',
              field_name: 'check_out_storage_condition',
              code: '',
            },
            {
              title: 'ตรวจสอบอุณหภูมิ (องศาเซลเซียส)',
              type: 'radio',
              field_name: 'check_temperature',
              code: '',
            },
            {
              title: 'ตรวจสอบเสียง (ดังผิดปรกติหรือไม่)',
              type: 'radio',
              field_name: 'check_sound',
              code: '',
            },
            {
              title: 'ตรวจสอบ Shelf Stript ป้ายราคา',
              type: 'radio',
              field_name: 'check_shelf_stript',
              code: '',
            },
            {
              title: 'ตรวจเช็คที่เปิดขวด',
              type: 'radio',
              field_name: 'check_bottle_opener',
              code: '',
            },
            {
              title: 'ตรวจเช็คการทำงานของมอเตอร์กระจายความเย็น',
              type: 'radio',
              field_name: 'check_operation_cooling_motor',
              code: '',
            },
            {
              title: 'ตรวจเช็คประตูตู้(ต้องปิดสนิท)',
              type: 'radio',
              field_name: 'check_cabinet_door',
              code: '',
            },
            {
              title: 'ตรวจเช็คสภาพล้อตู้เย็น',
              type: 'radio',
              field_name: 'check_condition_wheels',
              code: '',
            },
            {
              title: 'ตรวจเช็คเรียงสินค้าตู้เย็น',
              type: 'radio',
              field_name: 'check_sort_products',
              code: '',
            },
            {
              title: 'ตรวจเช็คความสะอาดภายในเครื่อง',
              type: 'radio',
              field_name: 'check_clean_inside_device.',
              code: '',
            },
            {
              title: 'ตรวจเช็คความสะอาดภายนอกเครื่อง',
              type: 'radio',
              field_name: 'check_clean_outside_device',
              code: '',
            },
          ],
        },
        {
          title:
            'รายการตรวจเช็คเครื่องที่เชื่อมโยงเครือข่าย(Machine with Conectivity)',
          type: 'D8',
          item: [
            {
              title: 'การทำงานของ Divece',
              type: 'radio',
              field_name: 'work_divece',
              code: '',
            },
            {
              title: 'Mapping ข้อมูลสำเร็จ',
              type: 'radio',
              field_name: 'mapping_success',
              code: '',
            },
            {
              title: 'CQR Parameter',
              type: 'radio',
              field_name: 'cqr_parameter',
              code: '',
            },
          ],
        },
        {
          title: 'รายการตรวจเช็คทั่วไป(Other)',
          type: 'O9',
          item: [
            {
              title: 'ใบประวัติเครื่อง',
              type: 'radio',
              field_name: 'machine_history',
              code: '',
            },
            {
              title: 'ซองพลาสติก',
              type: 'radio',
              field_name: 'plastic_bag',
              code: '',
            },
            {
              title: 'สติ๊กเกอร์แจ้งซ่อมเครื่อง',
              type: 'radio',
              field_name: 'machine_notification_sticker',
              code: '',
            },
            {
              title: 'สติ๊กเกอร์ Name plate/ CDE Code ',
              type: 'radio',
              field_name: 'sticker_name_plate',
              code: '',
            },
          ],
        },
        {
          title: 'รายการแจ้งลูกค้าได้รับทราบ(Recommend)',
          type: 'O9',
          item: [
            {
              title: 'แจ้งให้ลูกค้าทราบเรื่องคุณภาพเครื่องดื่ม',
              type: 'radio',
              field_name: 'notify_customer_drink',
              code: '',
            },
            {
              title:
                'แจ้งให้ลูกค้าทราบถึงปัญหาด้าน Pest Control ที่พบให้ลูกค้าทราบ',
              type: 'radio',
              field_name: 'notify_customer_pest_control',
              code: '',
            },
            {
              title:
                'อบรมให้ลูกค้าทราบเรื่องการใช้งานและบำรุงรักษาเครื่องและการแก้ไขปัญหาเบื้องต้น',
              type: 'radio',
              field_name: 'training_customers',
              code: '',
            },
          ],
        },
      ],
    },
  ];

  const data = qlChecklistData.filter(v => v.type == type)[0];
  return data;
};

export const SatisfactionAssessment = (data: any) => {
  console.log('SatisfactionAssessment=====>', data);
};

export const workOrderPmCheckList = (data: any) => {
  console.log('workOrderPmCheckList=====>', data);
};

export const getWorkOrder = (orderid: string) => {
  const order = mockDataWorkOrder();
  order.filter(v => v.orderid == orderid);
  return order[0];
};

export const getCategoryByType = (type: string) => {
  const categoryType: CatalogByObjectType[] = [
    {
      catalog_profile_has_catalog_id: 997,
      cat_profile: 'TCO',
      catalog: 'D',
      code_group: 'PLC',
      codegrp: [
        {
          catalog_code_group_has_code_id: 11284,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN01',
          short_text: 'ระบบน้ำไม่พร้อม',
        },
        {
          catalog_code_group_has_code_id: 11285,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN02',
          short_text: 'ระบบไฟฟ้าไม่พร้อม',
        },
        {
          catalog_code_group_has_code_id: 11286,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN03',
          short_text: 'พื้นที่ไม่พร้อมติดตั้ง',
        },
        {
          catalog_code_group_has_code_id: 11287,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN04',
          short_text: 'ลูกค้าปฏิเสธการรับเครื่อง',
        },
        {
          catalog_code_group_has_code_id: 11288,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN05',
          short_text: 'รุ่นเครื่องไม่ตรงตามที่ตกลง',
        },
        {
          catalog_code_group_has_code_id: 11289,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN06',
          short_text: 'ลูกค้ายังไม่สะดวกให้ติดตั้ง',
        },
        {
          catalog_code_group_has_code_id: 11290,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN07',
          short_text: 'ร้านปิด',
        },
        {
          catalog_code_group_has_code_id: 11291,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN08',
          short_text: 'ร้านปิดกิจการ',
        },
        {
          catalog_code_group_has_code_id: 11292,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN09',
          short_text: 'ลูกค้าขอเลื่อนวันติดตั้ง',
        },
        {
          catalog_code_group_has_code_id: 11293,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN10',
          short_text: 'ไม่เจอร้าน-ติดต่อลูกค้า/saleไม่ได้',
        },
        {
          catalog_code_group_has_code_id: 11294,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN11',
          short_text: 'ข้อมูลร้านไม่ถูกต้องกับหน้างาน',
        },
        {
          catalog_code_group_has_code_id: 11295,
          catalog: 'D',
          code_group: 'PLC',
          code: 'IN99',
          short_text: 'อื่นๆ',
        },
      ],
    },
    {
      catalog_profile_has_catalog_id: 998,
      cat_profile: 'TCO',
      catalog: 'D',
      code_group: 'RMC',
      codegrp: [
        {
          catalog_code_group_has_code_id: 11296,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM01',
          short_text: 'หน้างานไม่สามารถถอดถอนได้',
        },
        {
          catalog_code_group_has_code_id: 11297,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM02',
          short_text: 'ลูกค้ายังต้องการใช้เครื่องต่อ',
        },
        {
          catalog_code_group_has_code_id: 11298,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM03',
          short_text: 'ทรัพย์สินของลูกค้า (ตู้ ccp)',
        },
        {
          catalog_code_group_has_code_id: 11299,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM04',
          short_text: 'ร้านค้าปิด',
        },
        {
          catalog_code_group_has_code_id: 11300,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM05',
          short_text: 'ร้านปิดกิจการ',
        },
        {
          catalog_code_group_has_code_id: 11301,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM06',
          short_text: 'ไม่เจอร้าน-ติดต่อลูกค้าและ saleไม่ได้',
        },
        {
          catalog_code_group_has_code_id: 11302,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM07',
          short_text: 'หมายเลขอุปกรณ์ไม่ตรง',
        },
        {
          catalog_code_group_has_code_id: 11303,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM08',
          short_text: 'ไม่พบอุปกรณ์ ที่ร้านค้า',
        },
        {
          catalog_code_group_has_code_id: 11304,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM09',
          short_text: 'ข้อมูลร้านไม่ถูกต้องกับหน้างาน',
        },
        {
          catalog_code_group_has_code_id: 11305,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM10',
          short_text: 'ลูกค้าขอเลื่อน',
        },
        {
          catalog_code_group_has_code_id: 11306,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM11',
          short_text: 'ลูกค้าปฏิเสธถอนอุปกรณ์ รอคืนภาชนะ',
        },
        {
          catalog_code_group_has_code_id: 11307,
          catalog: 'D',
          code_group: 'RMC',
          code: 'RM99',
          short_text: 'อื่นๆ',
        },
      ],
    },
  ];

  const data = categoryType.filter(v => v.cat_profile == type);
  return data;
};

export const getCategoryByID = (id: string) => {
  const category = [
    {
      actual_id: 349457,
      orderid: '000041000028',
      work_order_obj: null,
      notif_no: null,
      problem_codegroup: 'TICM',
      posnr: 1,
      problem_code: 'IN01',
      damage_codegroup: 'TICM',
      damage_code: 'RM02',
      damage_text: 'D128 น้ำรั่วใต้เครื่อง',
      cause_codegroup: 'TICM',
      cause_code: 'RM06',
      cause_text: 'C190 ท่อน้ำทิ้งทางร้านอุดตัน',
      activity_codegroup: 'TICM',
      activity_code: 'IN08',
      activity_text: 'A106 ตรวจเช็คเครื่อง',
    },
  ];

  const data = category;
  return data;
};
